# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\研究生\铁路\code1.0\play_label\ui\info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 120)
        Dialog.setMinimumSize(QtCore.QSize(400, 120))
        Dialog.setMaximumSize(QtCore.QSize(400, 120))
        Dialog.setStyleSheet("background-color: rgb(22, 22, 22);\n"
"color: rgb(177, 177, 177);")
        self.label_msg = QtWidgets.QLabel(Dialog)
        self.label_msg.setGeometry(QtCore.QRect(10, 20, 370, 80))
        self.label_msg.setMinimumSize(QtCore.QSize(370, 80))
        self.label_msg.setMaximumSize(QtCore.QSize(370, 80))
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "message"))
