# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRect
from PyQt5.QtGui import QPainter, QPen, QImage, QPixmap
from PyQt5.QtWidgets import QFileDialog, QLabel, QMainWindow

from dao.label import MyLabel


class Ui_MainWindow(QMainWindow):
    def __init__(self, url):
        # 窗口初始化
        super(Ui_MainWindow, self).__init__()
        self.img_path = url          # 传入图片路径
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 652, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 652, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = MyLabel(self)
        self.label.setGeometry(QtCore.QRect(70, 70, 960, 540))
        self.label.setMinimumSize(QtCore.QSize(960, 540))
        self.label.setMaximumSize(QtCore.QSize(960, 540))
        self.label.setObjectName("label")

        jpg = QtGui.QPixmap(self.img_path).scaled(self.label.width(), self.label.height())
        self.label.img_path = jpg
        self.label.setPixmap(jpg)
        self.label.setCursor(Qt.CrossCursor)

        self.pushButton.clicked.connect(self.save_sample)
        self.pushButton_2.clicked.connect(self.back)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.pushButton_2.setText(_translate("MainWindow", "取消"))


    def save_sample(self):
        if self.label.labels:
            img_save_dir = "./save/img/" + self.label.labels[0] + "/"
            txt_save_dir = "./save/txt/" + self.label.labels[0] + "/"

        else:
            pass
        img_save_path = img_save_dir + "test.jpg"
        self.label.pixmap().toImage().save(img_save_path)  # 保存的图片不带矩形框
        txt_save_path = txt_save_dir + "test.txt"
        nums = len(self.label.rects)
        for idx in range(nums):
            cls, x_min, y_min = self.label.labels[idx], self.label.rects[idx].x(), self.label.rects[idx].y()
            x_max, y_max = x_min + self.label.rects[idx].width(), y_min + self.label.rects[idx].height()
            with open(txt_save_path, "a+") as f:
                f.write(cls + "," + str(x_min) + "," + str(y_min) + "," + str(x_max) + "," + str(y_max) + " ")

        self.label.rects.clear()            # 清空目标框，标签列表
        self.label.labels.clear()
        self.close()

    def back(self):
        self.label.rects.clear()            # 清空目标框，标签列表
        self.label.labels.clear()
        self.close()