# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\研究生\铁路\code1.0\play_label\ui\railway_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 777)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 777))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 777))
        MainWindow.setStyleSheet("background-color: rgb(22, 22, 22);\n"
"border: rgb(22, 22, 22);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grb_alarm = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_alarm.setGeometry(QtCore.QRect(930, 430, 651, 321))
        self.grb_alarm.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(177, 177, 177);")
        self.grb_alarm.setObjectName("grb_alarm")
        self.label_is_error = QtWidgets.QLabel(self.grb_alarm)
        self.label_is_error.setGeometry(QtCore.QRect(40, 40, 151, 51))
        self.label_is_error.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.label_is_error.setText("")
        self.label_is_error.setObjectName("label_is_error")
        self.teb_log = QtWidgets.QTextBrowser(self.grb_alarm)
        self.teb_log.setGeometry(QtCore.QRect(40, 110, 571, 201))
        self.teb_log.setStyleSheet("color: rgb(177, 177, 177);\n"
"background-color: rgb(29, 29, 29);")
        self.teb_log.setObjectName("teb_log")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(930, 10, 651, 411))
        self.groupBox.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(177, 177, 177);")
        self.groupBox.setObjectName("groupBox")
        self.label_error_img = QtWidgets.QLabel(self.groupBox)
        self.label_error_img.setGeometry(QtCore.QRect(10, 20, 631, 381))
        self.label_error_img.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.label_error_img.setText("")
        self.label_error_img.setObjectName("label_error_img")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 610, 911, 141))
        self.groupBox_2.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(177, 177, 177);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_open_video = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_open_video.setGeometry(QtCore.QRect(50, 20, 381, 41))
        self.btn_open_video.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.btn_open_video.setObjectName("btn_open_video")
        self.hslider_timeF = QtWidgets.QSlider(self.groupBox_2)
        self.hslider_timeF.setGeometry(QtCore.QRect(170, 100, 291, 22))
        self.hslider_timeF.setStyleSheet("")
        self.hslider_timeF.setMinimum(1)
        self.hslider_timeF.setMaximum(100)
        self.hslider_timeF.setSingleStep(25)
        self.hslider_timeF.setPageStep(5)
        self.hslider_timeF.setProperty("value", 25)
        self.hslider_timeF.setOrientation(QtCore.Qt.Horizontal)
        self.hslider_timeF.setObjectName("hslider_timeF")
        self.label_timeF = QtWidgets.QLabel(self.groupBox_2)
        self.label_timeF.setGeometry(QtCore.QRect(40, 100, 111, 21))
        self.label_timeF.setObjectName("label_timeF")
        self.btn_label_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_label_pic.setGeometry(QtCore.QRect(490, 20, 391, 41))
        self.btn_label_pic.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.btn_label_pic.setObjectName("btn_label_pic")
        self.btn_change_save_path = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_change_save_path.setGeometry(QtCore.QRect(490, 80, 391, 41))
        self.btn_change_save_path.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.btn_change_save_path.setObjectName("btn_change_save_path")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 911, 591))
        self.groupBox_3.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color: rgb(177, 177, 177);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_in_img = QtWidgets.QLabel(self.groupBox_3)
        self.label_in_img.setGeometry(QtCore.QRect(10, 20, 891, 531))
        self.label_in_img.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.label_in_img.setText("")
        self.label_in_img.setObjectName("label_in_img")
        self.probar_load = QtWidgets.QProgressBar(self.groupBox_3)
        self.probar_load.setEnabled(False)
        self.probar_load.setGeometry(QtCore.QRect(10, 563, 891, 16))
        self.probar_load.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.probar_load.setProperty("value", 0)
        self.probar_load.setTextVisible(False)
        self.probar_load.setObjectName("probar_load")
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.grb_alarm.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "铁路异物检测程序"))
        self.grb_alarm.setTitle(_translate("MainWindow", "警告信息"))
        self.groupBox.setTitle(_translate("MainWindow", "上一个异常帧"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作"))
        self.btn_open_video.setText(_translate("MainWindow", "打开视频文件"))
        self.label_timeF.setText(_translate("MainWindow", " 处理帧率：25"))
        self.btn_label_pic.setText(_translate("MainWindow", "打开标注文件"))
        self.btn_change_save_path.setText(_translate("MainWindow", "选择异常帧保存路径"))
        self.groupBox_3.setTitle(_translate("MainWindow", "视频流"))
